### ISSUE TITLE
Diverso path di installazione di SQL Server

### ISSUE THREAD

**Issue by Magicianred** [gsaielli/cave-serene#1]
Ho configurato diversamente l'installazione di SQL Server e questo genera un errore nel lancio dello script.
Trovare un modo per renderlo dinamico o segnalarlo nella documentazione.

Msg 5133, Level 16, State 1, Line 4
Directory lookup for the file "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CaveSerene.mdf" failed with the operating system error 3 (The system cannot find the path specified.).

Cambiando il PATH l'installazione è avvenuta correttamente.

**Comment by gsaielli** [comment]
Tutto lo script si può migliorare molto. E' stato generato automaticamente.
Appena trovo il tempo lo faccio. Se invece vuoi proporre un nuovo script è benvenuto!

Grazie

**Comment by Magicianred** [comment]
Grazie per la risposta :) sto provando ad installare il tutto in locale e segno qui sulle Issue le varie problematiche che sto incontrando.
Ho visto che si può far qualcosa con T-SQL andando a leggere il PATH nel registry con la funzione _xp_regread_

Ora sto installando VS2017 che con la versione 2019 mi da problemi con l'SDK target 4.5
vediamo :) 

Grazie a te

**Comment by gsaielli** [comment]
Ridotto il requisito di avere un SQL Server disponibile. Ora funziona con LocalDB. Prima bisogna sempre creare il DB a mano, per il resto ci sono gli script.
