### ISSUE TITLE
In compilazione ho questo errore: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found

### ISSUE THREAD

**Issue by Magicianred** [gsaielli/cave-serene#3]
Lo stesso con il ".NETFramework,Version=v4.5"

Ovviamente l'SDK era presente sulla mia macchina, l'ho riscaricato diverse volte ed installato, anche attraverso Visual Studio Installer, ma non era risolutivo.

E' un problema che non avevo mai affrontato prima, forse dovuto alle più recenti versioni di Visual Studio rispetto a quella con cui è stato creato il progetto.
Questo problema è sicuramente relativo mia macchina, da qualche parte nel progetto c'è un riferimento al path degli SDK che non permetteva di compilare.

Se qualcuno trova lo stesso problema io l'ho risolto in questo modo:

Nella cartella 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework' era presente solo la v.3.0 e la v.3.5, mentre in 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework' erano presenti tutti gli altri SDK
Ho copiato le versioni mancanti in 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework' e riaprendo visual studio non ho più il problema

Ora riparto dal repo iniziale e riprovo senza modificare il target a v.4.6.1

**Comment by Magicianred** [comment]
Nel mio caso non ha funzionato con il target '4.5' (non si può scaricare più l'SDK) ne con il '4.5.1', ma con la '4.6.1' si compila e si lancia

**Comment by gsaielli** [comment]
Portato a FW 4.6.1. Configurazione test: VS 2019 CE
